# Generated by Django 5.2.10 on 2026-02-23 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_event_type_alter_event_date_eventdate_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["-created_at"]},
        ),
    ]
