# Generated by Django 5.2.10 on 2026-01-08 11:20

import apps.notes.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.notes.models.note_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('note', models.ForeignKey(blank=True, help_text='Associated note (can be null for newly pasted images)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='notes.note')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_images', to='organizations.organization')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_note_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'note_images',
                'ordering': ['-created_at'],
            },
        ),
    ]
