# Generated by Django 5.2.10 on 2026-01-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_add_noteimage_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="written_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the note was originally written (for imported notes)",
                null=True,
            ),
        ),
    ]
