# Generated by Django 5.2.10 on 2026-01-13 00:45

from django.db import migrations, models


def backfill_is_imported(apps, schema_editor):
    """Set is_imported=True for all notes that have written_at set."""
    Note = apps.get_model('notes', 'Note')
    updated = Note.objects.filter(written_at__isnull=False).update(is_imported=True)
    print(f"Backfilled is_imported=True for {updated} notes with written_at set")


def reverse_backfill(apps, schema_editor):
    """Reverse: set is_imported=False for all notes."""
    Note = apps.get_model('notes', 'Note')
    Note.objects.all().update(is_imported=False)


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_add_written_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="is_imported",
            field=models.BooleanField(
                default=False,
                help_text="Whether this note was imported from external source",
            ),
        ),
        migrations.RunPython(backfill_is_imported, reverse_backfill),
    ]
