# Generated by Django 5.2.10 on 2026-01-13 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0004_add_is_imported"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteCashFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Stock price used for calculation",
                        max_digits=12,
                    ),
                ),
                (
                    "fcf_year_1",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="FCF per share forecast - Year 1",
                        max_digits=12,
                    ),
                ),
                (
                    "fcf_year_2",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="FCF per share forecast - Year 2",
                        max_digits=12,
                    ),
                ),
                (
                    "fcf_year_3",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="FCF per share forecast - Year 3",
                        max_digits=12,
                    ),
                ),
                (
                    "fcf_year_4",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="FCF per share forecast - Year 4",
                        max_digits=12,
                    ),
                ),
                (
                    "fcf_year_5",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="FCF per share forecast - Year 5",
                        max_digits=12,
                    ),
                ),
                (
                    "terminal_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Terminal value per share at end of Year 5",
                        max_digits=12,
                    ),
                ),
                (
                    "calculated_irr",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Calculated IRR as decimal (e.g., 0.15 = 15%)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "note",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_flow",
                        to="notes.note",
                    ),
                ),
            ],
            options={
                "db_table": "note_cash_flows",
            },
        ),
    ]
