# Generated by Django 5.2.10 on 2026-01-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0005_notecashflow"),
    ]

    operations = [
        migrations.AddField(
            model_name="notecashflow",
            name="ebit_ebitda_year_1",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="EBIT or EBITDA per share forecast - Year 1",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="notecashflow",
            name="ebit_ebitda_year_2",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="EBIT or EBITDA per share forecast - Year 2",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="notecashflow",
            name="ebit_ebitda_year_3",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="EBIT or EBITDA per share forecast - Year 3",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="notecashflow",
            name="ebit_ebitda_year_4",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="EBIT or EBITDA per share forecast - Year 4",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="notecashflow",
            name="ebit_ebitda_year_5",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="EBIT or EBITDA per share forecast - Year 5",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="notecashflow",
            name="revenue_year_1",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Revenue per share forecast - Year 1",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="notecashflow",
            name="revenue_year_2",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Revenue per share forecast - Year 2",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="notecashflow",
            name="revenue_year_3",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Revenue per share forecast - Year 3",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="notecashflow",
            name="revenue_year_4",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Revenue per share forecast - Year 4",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="notecashflow",
            name="revenue_year_5",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Revenue per share forecast - Year 5",
                max_digits=12,
                null=True,
            ),
        ),
    ]
