# Generated by Django 5.2.10 on 2026-01-20 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0006_notecashflow_ebit_ebitda_year_1_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteShareLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("allow_comments", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("last_viewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_share_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_links",
                        to="notes.note",
                    ),
                ),
            ],
            options={
                "db_table": "note_share_links",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NoteShareComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_name", models.CharField(blank=True, max_length=100)),
                ("author_email", models.EmailField(blank=True, max_length=254)),
                ("content", models.TextField(max_length=2000)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_approved", models.BooleanField(default=True)),
                ("is_hidden", models.BooleanField(default=False)),
                (
                    "share_link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="notes.notesharelink",
                    ),
                ),
            ],
            options={
                "db_table": "note_share_comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="notesharelink",
            index=models.Index(fields=["token"], name="note_share__token_5f236e_idx"),
        ),
        migrations.AddIndex(
            model_name="notesharelink",
            index=models.Index(
                fields=["note", "is_active"], name="note_share__note_id_1c9544_idx"
            ),
        ),
    ]
