# Generated by Django 5.2.10 on 2026-02-24 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0013_add_key_questions"),
        ("notes", "0007_add_note_share_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notes",
                to="companies.company",
            ),
        ),
    ]
