# Generated by Django 5.2.11 on 2026-03-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_alter_note_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='Whether this note is currently a draft'),
        ),
    ]
