# Generated by Django 5.2.10 on 2026-01-15 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0012_add_revenue_profitability_to_valuation"),
        ("organizations", "0002_add_organization_invite"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(max_length=500)),
                ("summary", models.TextField(help_text="AI-generated summary")),
                ("source_url", models.URLField(max_length=2000)),
                ("source_name", models.CharField(max_length=100)),
                (
                    "source_type",
                    models.CharField(
                        choices=[("web", "Web Search"), ("sec_edgar", "SEC EDGAR")],
                        default="web",
                        max_length=20,
                    ),
                ),
                (
                    "importance",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        blank=True,
                        help_text="Event category: earnings, management, M&A, regulatory, product, legal, analyst, other",
                        max_length=50,
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(help_text="When the article was published"),
                ),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                ("is_starred", models.BooleanField(default=False)),
                ("url_hash", models.CharField(db_index=True, max_length=64)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news_items",
                        to="companies.company",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news_items",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company News",
                "verbose_name_plural": "Company News",
                "ordering": ["-published_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "-published_at"],
                        name="news_compan_company_384da1_idx",
                    ),
                    models.Index(
                        fields=["organization", "-published_at"],
                        name="news_compan_organiz_e4820f_idx",
                    ),
                    models.Index(
                        fields=["importance", "-published_at"],
                        name="news_compan_importa_abce27_idx",
                    ),
                ],
                "unique_together": {("company", "url_hash")},
            },
        ),
    ]
