# Generated by Django 5.2.11 on 2026-02-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companynews',
            name='publisher_domain',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
