# Generated by Django 5.2.11 on 2026-02-27 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_add_publisher_domain'),
        ('organizations', '0002_add_organization_invite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companynews',
            name='is_starred',
        ),
        migrations.AddField(
            model_name='companynews',
            name='feedback',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Thumbs Up'), (-1, 'Thumbs Down')], default=None, null=True),
        ),
        migrations.CreateModel(
            name='BlacklistedDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='Domain to block (e.g., msn.com)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_domains', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Blacklisted Domain',
                'verbose_name_plural': 'Blacklisted Domains',
                'ordering': ['domain'],
                'unique_together': {('organization', 'domain')},
            },
        ),
    ]
