# Generated by Django 5.2.11 on 2026-03-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_feedback_replace_starred'),
    ]

    operations = [
        migrations.AddField(
            model_name='companynews',
            name='feedback_reason',
            field=models.CharField(blank=True, choices=[('bad_source', 'This website is no good'), ('not_relevant', 'Subject is not relevant')], default=None, max_length=20, null=True),
        ),
    ]
