# Generated by Django 5.2.10 on 2026-01-08 05:55

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('portfolio', 'Portfolio'), ('on_deck', 'On Deck'), ('watchlist', 'Watchlist'), ('passed', 'Passed'), ('archived', 'Archived')], db_index=True, default='watchlist', max_length=30)),
                ('sector', models.CharField(blank=True, choices=[('technology', 'Technology'), ('healthcare', 'Healthcare'), ('financials', 'Financials'), ('consumer_discretionary', 'Consumer Discretionary'), ('consumer_staples', 'Consumer Staples'), ('industrials', 'Industrials'), ('energy', 'Energy'), ('materials', 'Materials'), ('utilities', 'Utilities'), ('real_estate', 'Real Estate'), ('communications', 'Communications'), ('other', 'Other')], db_index=True, max_length=30)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('thesis', models.TextField(blank=True, help_text='Investment thesis summary')),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, help_text='Market cap in USD', max_digits=20, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'db_table': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('exchange', models.CharField(blank=True, max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickers', to='companies.company')),
            ],
            options={
                'db_table': 'company_tickers',
                'ordering': ['-is_primary', 'symbol'],
            },
        ),
        migrations.AddIndex(
            model_name='company',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='companies_search__ec0013_gin'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['organization', 'status'], name='companies_organiz_575bce_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['organization', 'sector'], name='companies_organiz_390e52_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['organization', '-updated_at'], name='companies_organiz_7508cd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('organization', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='companyticker',
            unique_together={('company', 'symbol', 'exchange')},
        ),
    ]
