# Generated by Django 5.2.10 on 2026-01-08 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('shares_outstanding', models.DecimalField(decimal_places=2, help_text='Shares outstanding (in millions)', max_digits=20)),
                ('fcf_year_1', models.DecimalField(decimal_places=2, help_text='FCF per share forecast - Year 1', max_digits=12)),
                ('fcf_year_2', models.DecimalField(decimal_places=2, help_text='FCF per share forecast - Year 2', max_digits=12)),
                ('fcf_year_3', models.DecimalField(decimal_places=2, help_text='FCF per share forecast - Year 3', max_digits=12)),
                ('fcf_year_4', models.DecimalField(decimal_places=2, help_text='FCF per share forecast - Year 4', max_digits=12)),
                ('fcf_year_5', models.DecimalField(decimal_places=2, help_text='FCF per share forecast - Year 5', max_digits=12)),
                ('terminal_value', models.DecimalField(decimal_places=2, help_text='Terminal value per share at end of Year 5', max_digits=12)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, help_text='Current stock price (auto-fetched from Yahoo Finance)', max_digits=12, null=True)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Manual price override (takes precedence over fetched price)', max_digits=12, null=True)),
                ('price_last_updated', models.DateTimeField(blank=True, help_text='When price was last fetched', null=True)),
                ('calculated_irr', models.DecimalField(blank=True, decimal_places=4, help_text='Calculated IRR as decimal (e.g., 0.15 = 15%)', max_digits=8, null=True)),
                ('irr_last_calculated', models.DateTimeField(blank=True, null=True)),
                ('as_of_date', models.DateField(help_text='Date these estimates are based on')),
                ('notes', models.TextField(blank=True, help_text='Notes about valuation assumptions')),
                ('is_active', models.BooleanField(default=True, help_text='Only one active valuation per company')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'company_valuations',
                'ordering': ['-as_of_date', '-created_at'],
                'indexes': [models.Index(fields=['company', 'is_active'], name='company_val_company_c25b81_idx'), models.Index(fields=['-calculated_irr'], name='company_val_calcula_21a74e_idx')],
            },
        ),
    ]
