# Generated by Django 5.2.10 on 2026-01-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_add_companyvaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='alert_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price at which to consider deeper research', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='alert_price_reason',
            field=models.CharField(blank=True, help_text='Brief explanation of why this alert price was chosen', max_length=500),
        ),
        migrations.AddField(
            model_name='company',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current stock price (auto-fetched)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='price_last_updated',
            field=models.DateTimeField(blank=True, help_text='When price was last fetched', null=True),
        ),
    ]
