# Generated by Django 5.2.10 on 2026-01-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_add_alert_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ev_ebitda',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enterprise Value / EBITDA ratio', max_digits=10, null=True),
        ),
    ]
