# Generated by Django 5.2.10 on 2026-01-08 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_add_ev_ebitda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValuationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcf_year_1', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fcf_year_2', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fcf_year_3', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fcf_year_4', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fcf_year_5', models.DecimalField(decimal_places=2, max_digits=12)),
                ('terminal_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('shares_outstanding', models.DecimalField(decimal_places=2, max_digits=20)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('calculated_irr', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, help_text='Optional note about this change', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('valuation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='companies.companyvaluation')),
            ],
            options={
                'db_table': 'valuation_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
