# Generated by Django 5.2.10 on 2026-01-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_add_valuation_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='business_summary',
            field=models.TextField(blank=True, help_text='Business description from Yahoo Finance'),
        ),
    ]
