# Generated by Django 5.2.10 on 2026-01-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0007_add_ai_summary_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="ebit_metric",
            field=models.CharField(
                choices=[("ebit", "EBIT"), ("ebitda", "EBITDA")],
                default="ebitda",
                help_text="Whether to track EBIT or EBITDA for this company",
                max_length=10,
            ),
        ),
    ]
