# Generated by Django 5.2.10 on 2026-01-13 19:23

from django.db import migrations, models


def convert_ebit_metric_values(apps, schema_editor):
    """Convert old choice values to display names."""
    Company = apps.get_model('companies', 'Company')
    for company in Company.objects.all():
        if company.profitability_metric == 'ebit':
            company.profitability_metric = 'EBIT'
        elif company.profitability_metric == 'ebitda':
            company.profitability_metric = 'EBITDA'
        company.save(update_fields=['profitability_metric'])


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0008_company_ebit_metric"),
    ]

    operations = [
        # First rename the field to preserve data
        migrations.RenameField(
            model_name="company",
            old_name="ebit_metric",
            new_name="profitability_metric",
        ),
        # Then alter the field properties
        migrations.AlterField(
            model_name="company",
            name="profitability_metric",
            field=models.CharField(
                blank=True,
                default="EBITDA",
                help_text="Name of the profitability metric to track (e.g., EBITDA, EBIT, Operating Income)",
                max_length=50,
            ),
        ),
        # Convert old choice values (ebit/ebitda) to display names (EBIT/EBITDA)
        migrations.RunPython(convert_ebit_metric_values, migrations.RunPython.noop),
    ]
