# Generated by Django 5.2.10 on 2026-01-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0009_rename_ebit_metric_to_profitability_metric"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyvaluation",
            name="shares_outstanding",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Shares outstanding (in millions)",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="valuationhistory",
            name="shares_outstanding",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
    ]
