# Generated by Django 5.2.10 on 2026-01-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0011_restructure_company_categories"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="company",
            new_name="companies_organiz_b8e714_idx",
            old_name="companies_c_organiz_d5f8e2_idx",
        ),
        migrations.AddField(
            model_name="companyvaluation",
            name="ebit_ebitda_year_1",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Profitability metric forecast - Year 1",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="companyvaluation",
            name="ebit_ebitda_year_2",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Profitability metric forecast - Year 2",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="companyvaluation",
            name="ebit_ebitda_year_3",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Profitability metric forecast - Year 3",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="companyvaluation",
            name="ebit_ebitda_year_4",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Profitability metric forecast - Year 4",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="companyvaluation",
            name="ebit_ebitda_year_5",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Profitability metric forecast - Year 5",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="companyvaluation",
            name="revenue_year_1",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Revenue forecast - Year 1",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="companyvaluation",
            name="revenue_year_2",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Revenue forecast - Year 2",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="companyvaluation",
            name="revenue_year_3",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Revenue forecast - Year 3",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="companyvaluation",
            name="revenue_year_4",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Revenue forecast - Year 4",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="companyvaluation",
            name="revenue_year_5",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Revenue forecast - Year 5",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="alert_price_low",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Low price alert - triggers when price drops to this level (long opportunity)",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="alert_reason",
            field=models.CharField(
                blank=True,
                help_text="Brief explanation of why these alert prices were chosen",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="status",
            field=models.CharField(
                choices=[
                    ("long_book", "Long Book"),
                    ("short_book", "Short Book"),
                    ("on_deck", "On Deck"),
                    ("watchlist", "Watch List"),
                    ("passed", "Passed"),
                    ("archived", "Archived"),
                ],
                db_index=True,
                default="watchlist",
                max_length=30,
            ),
        ),
    ]
