# Generated by Django 5.2.10 on 2026-01-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0012_add_revenue_profitability_to_valuation"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="key_questions",
            field=models.TextField(
                blank=True,
                help_text="Key questions to investigate about this company (one per line)",
            ),
        ),
    ]
