# Generated by Django 5.2.10 on 2026-01-09 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0006_add_business_summary'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('category_type', models.CharField(choices=[('maintenance', 'Maintenance'), ('research', 'Research')], default='research', max_length=20)),
                ('color', models.CharField(default='#6B7280', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_categories', to='organizations.organization')),
            ],
            options={
                'db_table': 'todo_categories',
                'ordering': ['order', 'name'],
                'unique_together': {('organization', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('todo_type', models.CharField(choices=[('quarterly_update', 'Quarterly Update'), ('investor_letter', 'Investor Letter Review'), ('custom', 'Custom')], db_index=True, default='custom', max_length=30)),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_generated', models.BooleanField(default=False)),
                ('quarter', models.CharField(blank=True, help_text='Quarter this todo relates to (e.g., 2024-Q1)', max_length=7)),
                ('fiscal_year', models.PositiveIntegerField(blank=True, null=True)),
                ('investor_letter_notes', models.TextField(blank=True, help_text='Notes about investor letters read this quarter')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='companies.company')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_todos', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todos', to='todos.todocategory')),
            ],
            options={
                'db_table': 'todos',
                'ordering': ['is_completed', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchlistQuickAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('alert_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('note', models.CharField(blank=True, help_text='Brief note about why this company is interesting', max_length=500)),
                ('is_processed', models.BooleanField(default=False, help_text='Whether this has been converted to a Company')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_company', models.ForeignKey(blank=True, help_text='The Company created from this quick add', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quick_add', to='companies.company')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_additions', to='todos.todo')),
            ],
            options={
                'db_table': 'watchlist_quick_adds',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['organization', 'is_completed'], name='todos_organiz_e1a805_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['organization', 'company'], name='todos_organiz_055816_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['organization', 'todo_type'], name='todos_organiz_ef13b4_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['organization', 'quarter'], name='todos_organiz_61f3ab_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['company', 'is_completed'], name='todos_company_c31027_idx'),
        ),
    ]
