# Generated by Django 5.2.10 on 2026-01-12 18:55

from django.db import migrations, models


def convert_research_to_deep_dives(apps, schema_editor):
    """Convert any existing 'research' categories to 'deep_dives'."""
    TodoCategory = apps.get_model('todos', 'TodoCategory')
    TodoCategory.objects.filter(category_type='research').update(
        category_type='deep_dives',
        name='Deep Dives',
        slug='deep-dives'
    )


def reverse_deep_dives_to_research(apps, schema_editor):
    """Reverse: convert 'deep_dives' back to 'research'."""
    TodoCategory = apps.get_model('todos', 'TodoCategory')
    TodoCategory.objects.filter(category_type='deep_dives').update(
        category_type='research',
        name='Research',
        slug='research'
    )


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        # First convert existing data
        migrations.RunPython(
            convert_research_to_deep_dives,
            reverse_deep_dives_to_research
        ),
        # Then alter the field choices
        migrations.AlterField(
            model_name="todocategory",
            name="category_type",
            field=models.CharField(
                choices=[
                    ("maintenance", "Maintenance"),
                    ("deep_dives", "Deep Dives"),
                    ("marketing", "Marketing"),
                ],
                default="deep_dives",
                max_length=20,
            ),
        ),
    ]
