# Generated by Django 5.2.10 on 2026-01-12 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_add_written_at"),
        ("todos", "0002_alter_todocategory_category_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="completion_note",
            field=models.ForeignKey(
                blank=True,
                help_text="Note created as evidence of completion",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="completed_todos",
                to="notes.note",
            ),
        ),
    ]
