# Generated by Django 5.2.10 on 2026-01-13 15:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0007_add_ai_summary_fields"),
        ("notes", "0004_add_is_imported"),
        ("organizations", "0002_add_organization_invite"),
        ("todos", "0003_todo_completion_note"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="priority",
            field=models.CharField(
                choices=[
                    ("high", "High"),
                    ("medium", "Medium"),
                    ("low", "Low"),
                    ("none", "None"),
                ],
                db_index=True,
                default="none",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="todocategory",
            name="category_type",
            field=models.CharField(
                choices=[
                    ("maintenance", "Maintenance"),
                    ("idea_generation", "Idea Generation"),
                    ("marketing", "Marketing"),
                ],
                default="idea_generation",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="todo",
            index=models.Index(
                fields=["organization", "priority"], name="todos_organiz_d54d17_idx"
            ),
        ),
    ]
