# Generated by Django 5.2.10 on 2026-01-16 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0006_notecashflow_ebit_ebitda_year_1_and_more"),
        ("todos", "0004_todo_priority_alter_todocategory_category_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="source_note",
            field=models.ForeignKey(
                blank=True,
                help_text='Note this todo was created from (e.g., "finish this note")',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="todos",
                to="notes.note",
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="todo_type",
            field=models.CharField(
                choices=[
                    ("quarterly_update", "Quarterly Update"),
                    ("investor_letter", "Investor Letter Review"),
                    ("note_todo", "Note Todo"),
                    ("custom", "Custom"),
                ],
                db_index=True,
                default="custom",
                max_length=30,
            ),
        ),
    ]
