# Generated by Django 5.2.10 on 2026-01-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0005_add_source_note_to_todo"),
    ]

    operations = [
        migrations.AddField(
            model_name="todocategory",
            name="is_system",
            field=models.BooleanField(
                default=False, help_text="System categories cannot be deleted"
            ),
        ),
        migrations.AlterField(
            model_name="todocategory",
            name="category_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("maintenance", "Maintenance"),
                    ("idea_generation", "Idea Generation"),
                    ("marketing", "Marketing"),
                ],
                help_text="System category type (optional). Leave blank for custom categories.",
                max_length=20,
                null=True,
            ),
        ),
    ]
