# Generated by Django 5.2.10 on 2026-01-21 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0012_add_revenue_profitability_to_valuation"),
        ("notes", "0007_add_note_share_models"),
        ("organizations", "0002_add_organization_invite"),
        ("todos", "0006_flexible_categories"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                help_text="User this todo is assigned to (for personal todos)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_todos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="todo",
            name="scope",
            field=models.CharField(
                choices=[("personal", "Personal"), ("organization", "Team")],
                db_index=True,
                default="personal",
                help_text="Personal todos are only visible to the assigned user",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="todo",
            index=models.Index(
                fields=["organization", "scope"], name="todos_organiz_784e4d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="todo",
            index=models.Index(
                fields=["scope", "assigned_to"], name="todos_scope_0cc9ec_idx"
            ),
        ),
    ]
