# Generated by Django 5.2.10 on 2026-01-21 15:05

from django.db import migrations


def migrate_todos_to_personal(apps, schema_editor):
    """
    Migrate all existing todos to personal scope and assign to Evan Tindell.

    Since the schema migration sets default scope='personal', we just need to
    assign existing todos to the user.
    """
    Todo = apps.get_model('todos', 'Todo')
    User = apps.get_model('users', 'User')

    # Find user Evan Tindell by name or email
    evan = User.objects.filter(
        first_name__icontains='evan'
    ).first()

    if not evan:
        # Try by email
        evan = User.objects.filter(
            email__icontains='evan'
        ).first()

    if not evan:
        # Fallback: get the first user if no Evan found
        evan = User.objects.first()

    if evan:
        # Update all todos that are personal scope but have no assigned_to
        # (these are the pre-existing todos that got the default personal scope)
        Todo.objects.filter(
            scope='personal',
            assigned_to__isnull=True
        ).update(
            assigned_to=evan
        )


def reverse_migration(apps, schema_editor):
    """
    Reverse migration: set all todos back to organization scope.
    """
    Todo = apps.get_model('todos', 'Todo')
    Todo.objects.all().update(
        scope='organization',
        assigned_to=None
    )


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0007_add_scope_and_assigned_to"),
    ]

    operations = [
        migrations.RunPython(migrate_todos_to_personal, reverse_migration),
    ]
