# Generated by Django 5.2.11 on 2026-04-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0010_update_priority_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todo_type',
            field=models.CharField(choices=[('quarterly_update', 'Quarterly Update'), ('investor_letter', 'Investor Letter Review'), ('note_todo', 'Note Todo'), ('custom', 'Custom'), ('waiting_on_ryan', 'Waiting on Ryan')], db_index=True, default='custom', max_length=30),
        ),
    ]
