# Generated by Django 5.2.11 on 2026-03-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceevidence',
            name='text_content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
