# Generated by Django 5.2.11 on 2026-03-12 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_surveyquestion_employeecertificationstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancetask',
            name='migrated_to_survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migrated_from_tasks', to='compliance.surveyassignment'),
        ),
    ]
