# Generated by Django 5.2.11 on 2026-03-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0004_compliancetask_migrated_to_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Internal notes or migration source info'),
        ),
    ]
