# Generated by Django 5.2.10 on 2026-04-04 14:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def gen_uuid(apps, schema_editor):
    SurveyAssignment = apps.get_model('compliance', 'SurveyAssignment')
    for row in SurveyAssignment.objects.all():
        row.token = uuid.uuid4()
        row.save(update_fields=['token'])


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0005_surveyresponse_description"),
        ("organizations", "0002_add_organization_invite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: Add token without unique constraint
        migrations.AddField(
            model_name="surveyassignment",
            name="token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        # Step 2: Populate existing rows with unique UUIDs
        migrations.RunPython(gen_uuid, migrations.RunPython.noop),
        # Step 3: Make token unique and non-null
        migrations.AlterField(
            model_name="surveyassignment",
            name="token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name="SurveyDistribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("email_sent", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "compliance_task",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="survey_distribution",
                        to="compliance.compliancetask",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)ss",
                        to="organizations.organization",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distributions",
                        to="compliance.surveyversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
            },
        ),
        migrations.AddField(
            model_name="surveyassignment",
            name="distribution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assignments",
                to="compliance.surveydistribution",
            ),
        ),
    ]
