# Generated by Django 5.2.12 on 2026-03-22 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0005_surveyresponse_description'),
        ('organizations', '0002_add_organization_invite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compliancesettings',
            name='has_material_brochure_changes',
        ),
        migrations.RemoveField(
            model_name='compliancesettings',
            name='iard_renewal_window_end',
        ),
        migrations.RemoveField(
            model_name='compliancesettings',
            name='iard_renewal_window_start',
        ),
        migrations.RemoveField(
            model_name='compliancesettings',
            name='is_form_13f_applicable',
        ),
        migrations.RemoveField(
            model_name='compliancesettings',
            name='is_form_crs_applicable',
        ),
        migrations.RemoveField(
            model_name='compliancesettings',
            name='is_form_pf_applicable',
        ),
        migrations.RemoveField(
            model_name='compliancesettings',
            name='is_privacy_notice_annual_required',
        ),
        migrations.RemoveField(
            model_name='compliancesettings',
            name='require_evidence_for_completion',
        ),
        migrations.AddField(
            model_name='compliancesettings',
            name='aml_cft_target_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compliancesettings',
            name='domicile_state',
            field=models.CharField(default='US-CA', max_length=10),
        ),
        migrations.AddField(
            model_name='compliancesettings',
            name='entity_jurisdiction',
            field=models.CharField(default='US-DE', max_length=10),
        ),
        migrations.AddField(
            model_name='compliancesettings',
            name='firm_crd_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='compliancesettings',
            name='fund_admin_compliance_contact',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='compliancesettings',
            name='fund_admin_compliance_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='compliancesettings',
            name='primary_compliance_counsel',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='compliancesettings',
            name='registration_type',
            field=models.CharField(choices=[('ERA_VENTURE_CAPITAL', 'ERA Venture Capital'), ('ERA_PRIVATE_FUND', 'ERA Private Fund'), ('STATE_EXEMPT', 'State Exempt'), ('REGISTERED_RIA', 'Registered RIA')], default='ERA_PRIVATE_FUND', max_length=30),
        ),
        migrations.AddField(
            model_name='compliancetask',
            name='actual_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='compliancetask',
            name='delegated_to',
            field=models.CharField(choices=[('INTERNAL', 'Internal'), ('COMPLIANCE_COUNSEL', 'Compliance Counsel'), ('FUND_ADMIN', 'Fund Admin')], default='INTERNAL', max_length=20),
        ),
        migrations.AddField(
            model_name='compliancetask',
            name='delegated_to_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='compliancetask',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='compliancetask',
            name='period_label',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='compliancetask',
            name='reminder_sent_30',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compliancetask',
            name='reminder_sent_7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compliancetask',
            name='reminder_sent_90',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='complianceauditlog',
            name='action_type',
            field=models.CharField(choices=[('STATUS_CHANGE', 'Status Change'), ('NOTE_EDIT', 'Note Edit'), ('EVIDENCE_ADD', 'Evidence Added'), ('EVIDENCE_REMOVE', 'Evidence Removed'), ('TASK_EDIT', 'Task Edit'), ('TASK_CREATED', 'Task Created'), ('TEMPLATE_TOGGLE', 'Template Toggle'), ('OBLIGATION_CHANGE', 'Obligation Change'), ('JURISDICTION_ADD', 'Jurisdiction Added'), ('TASK_DELEGATED', 'Task Delegated'), ('TASKS_GENERATED', 'Tasks Generated')], max_length=30),
        ),
        migrations.CreateModel(
            name='ComplianceObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('frequency', models.CharField(choices=[('ONE_TIME', 'One Time'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUAL', 'Annual'), ('EVENT_DRIVEN', 'Event Driven')], max_length=20)),
                ('default_due_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('default_due_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('quarter', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, default='', max_length=500)),
                ('conditional_flag', models.CharField(blank=True, default='', max_length=100)),
                ('owner_role', models.CharField(blank=True, default='', max_length=100)),
                ('suggested_evidence', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('FORM_ADV', 'Form ADV'), ('BLUE_SKY', 'Blue Sky'), ('FORM_D', 'Form D'), ('FORM_PF', 'Form PF'), ('AML_CFT', 'AML/CFT'), ('STATE_NOTICE', 'State Notice'), ('INTERNATIONAL', 'International'), ('MONTHLY_CLOSE', 'Monthly Close'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('jurisdiction', models.CharField(blank=True, default='', max_length=10)),
                ('advance_notice_days', models.PositiveIntegerField(default=30)),
                ('due_date_reference', models.CharField(choices=[('AFTER_EVENT', 'After Event'), ('BEFORE_EVENT', 'Before Event')], default='AFTER_EVENT', max_length=20)),
                ('regulatory_reference', models.TextField(blank=True, default='')),
                ('filing_url', models.URLField(blank=True, default='', max_length=2000)),
                ('is_placeholder', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['default_due_month', 'default_due_day', 'title'],
            },
        ),
        migrations.AddField(
            model_name='compliancetask',
            name='obligation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='compliance.complianceobligation'),
        ),
        migrations.AlterField(
            model_name='compliancetask',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='compliance.complianceobligation'),
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('entity_type', models.CharField(choices=[('LP', 'Limited Partnership'), ('LLC', 'Limited Liability Company'), ('LTD', 'Limited Company'), ('GP', 'General Partner'), ('OTHER', 'Other')], default='LP', max_length=20)),
                ('entity_jurisdiction', models.CharField(default='US-DE', max_length=10)),
                ('sec_file_number', models.CharField(blank=True, default='', max_length=50)),
                ('edgar_cik', models.CharField(blank=True, default='', max_length=20)),
                ('inception_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='compliancetask',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_tasks', to='compliance.fund'),
        ),
        migrations.CreateModel(
            name='FundPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('crd_number', models.CharField(blank=True, default='', max_length=20)),
                ('title', models.CharField(default='', max_length=100)),
                ('residency_jurisdiction', models.CharField(default='', max_length=10)),
                ('is_us_resident', models.BooleanField(default=True)),
                ('requires_adv_nr', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principals', to='compliance.fund')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InvestorJurisdiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jurisdiction_code', models.CharField(max_length=10)),
                ('jurisdiction_name', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=5)),
                ('first_sale_date', models.DateField(blank=True, null=True)),
                ('blue_sky_filed', models.BooleanField(default=False)),
                ('blue_sky_filing_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_jurisdictions', to='compliance.fund')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['jurisdiction_code'],
                'unique_together': {('fund', 'jurisdiction_code')},
            },
        ),
        migrations.DeleteModel(
            name='ComplianceTaskTemplate',
        ),
    ]
