# Generated by Django 5.2.12 on 2026-03-23 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0006_era_compliance_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorjurisdiction',
            name='amount_sold',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='investorjurisdiction',
            name='blue_sky_expires',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investorjurisdiction',
            name='investors_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investorjurisdiction',
            name='nasaa_accession',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='investorjurisdiction',
            name='nasaa_efd_id',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
