# Generated by Django 5.2.10 on 2026-04-04 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0006_add_survey_distribution_and_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="compliancetasktemplate",
            name="survey_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task_templates",
                to="compliance.surveytemplate",
            ),
        ),
    ]
