# Generated by Django 5.2.11 on 2026-04-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0008_link_task_templates_to_surveys'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyassignment',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', help_text='CCO notes when rejecting a submission'),
        ),
    ]
