# Generated by Django 5.2.11 on 2026-04-16 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0014_remove_companyvaluation_price_override'),
        ('organizations', '0002_add_organization_invite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalSourceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('cybozu_ct_subdomains', 'Cybozu CT Subdomains')], max_length=50)),
                ('name', models.CharField(help_text='Display name for this signal config', max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
                ('settings_json', models.JSONField(blank=True, default=dict, help_text='Source-specific settings')),
                ('ignore_keywords', models.JSONField(blank=True, default=list, help_text='Keywords to flag subdomains as non-candidate (e.g. test, staging)')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_configs', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'signal_source_configs',
                'ordering': ['company__name', 'source'],
                'unique_together': {('organization', 'company', 'source')},
            },
        ),
        migrations.CreateModel(
            name='SignalSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=10)),
                ('raw_items_seen', models.IntegerField(default=0)),
                ('unique_domains_parsed', models.IntegerField(default=0)),
                ('created_count', models.IntegerField(default=0)),
                ('updated_count', models.IntegerField(default=0)),
                ('excluded_count', models.IntegerField(default=0)),
                ('error_text', models.TextField(blank=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='signals.signalsourceconfig')),
            ],
            options={
                'db_table': 'signal_sync_runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificateSubdomainObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_domain', models.CharField(max_length=255)),
                ('fqdn', models.CharField(max_length=512)),
                ('tenant_label', models.CharField(blank=True, help_text='e.g. "clientname" from clientname.kintone.com', max_length=255)),
                ('label_depth', models.PositiveSmallIntegerField(help_text='Number of labels before the base domain')),
                ('tenant_candidate', models.BooleanField(default=False, help_text='True if depth==1 and label is not in ignore list')),
                ('is_excluded', models.BooleanField(default=False)),
                ('exclude_reason', models.CharField(blank=True, max_length=255)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('last_cert_logged_at', models.DateTimeField(blank=True, null=True)),
                ('cert_not_before', models.DateTimeField(blank=True, null=True)),
                ('cert_not_after', models.DateTimeField(blank=True, null=True)),
                ('issuer_name', models.CharField(blank=True, max_length=512)),
                ('observation_count', models.IntegerField(default=1)),
                ('source_url', models.URLField(blank=True, max_length=1024)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(help_text='Denormalized FK for easier querying', on_delete=django.db.models.deletion.CASCADE, related_name='ct_observations', to='companies.company')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='signals.signalsourceconfig')),
            ],
            options={
                'db_table': 'certificate_subdomain_observations',
                'indexes': [models.Index(fields=['company'], name='certificate_company_ef943f_idx'), models.Index(fields=['base_domain'], name='certificate_base_do_c78ee6_idx'), models.Index(fields=['tenant_candidate'], name='certificate_tenant__6165e4_idx'), models.Index(fields=['first_seen_at'], name='certificate_first_s_44f140_idx'), models.Index(fields=['last_seen_at'], name='certificate_last_se_1e5ddf_idx')],
                'unique_together': {('config', 'fqdn')},
            },
        ),
    ]
