# Generated by Django 5.2.11 on 2026-04-10 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0014_remove_companyvaluation_price_override'),
        ('organizations', '0002_add_organization_invite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('as_of_date', models.DateField()),
                ('source_file', models.FileField(upload_to='portfolio_snapshots/')),
                ('extraction_raw', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('total_irr', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('total_volatility', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-as_of_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('name_extracted', models.CharField(blank=True, max_length=255)),
                ('current_weight', models.DecimalField(decimal_places=4, max_digits=6)),
                ('proposed_weight', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('irr', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('irr_source', models.CharField(choices=[('valuation', 'From Valuation Model'), ('manual', 'Manual Entry')], default='valuation', max_length=20)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='portfolio.portfoliosnapshot')),
            ],
            options={
                'ordering': ['-current_weight'],
            },
        ),
    ]
