# Generated by Django 5.2.11 on 2026-03-12 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_add_organization_invite'),
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchjob',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization'),
        ),
    ]
